// LOCALHOST 
### Get all recipes
GET http://localhost:8080/recipes 

### Get one recipe
GET http://localhost:8080/recipes/6359a5f35d6e75e725998db6 

### Create recipe
POST http://localhost:8080/recipes HTTP/1.1
content-type: application/json

{
    "name": "NewestRecipe",
    "ingredients": ["5 amazing ingredients", "2 amazing ingredients"],
    "directions": ["put them all together", "cook them"],
    "groceryList": ["first", "second", "third"],
    "mealType": "entree"
}

### Update recipe
PUT http://localhost:8080/recipes/6359a5f35d6e75e725998db6 HTTP/1.1
content-type: application/json

{
    "name": "NewestRecipe",
    "ingredients": ["7 amazing ingredients", "2 amazing ingredients"],
    "directions": ["put them all together", "cook them"],
    "groceryList": ["first", "second"],
    "mealType": "entree"
}


### Delete recipe
DELETE http://localhost:8080/recipes/6359a5f35d6e75e725998db6 HTTP/1.1


### Get all days
GET http://localhost:8080/days 

### Get one day
GET http://localhost:8080/days/63487efbd373ea68cf1215f3 

### Create day
POST http://localhost:8080/days HTTP/1.1
content-type: application/json

{
    "name": "NewDay",
    "mealID":""
}

### Update day
PUT http://localhost:8080/days/6359a6695d6e75e725998db7 HTTP/1.1
content-type: application/json

{
    "name": "NewDay2",
    "mealID":""
}

### Delete day
DELETE http://localhost:8080/days/6359a6695d6e75e725998db7 HTTP/1.1


// PRODUCTION Deploy 
### Get all recipes
GET https://jw-341-projecttwo.onrender.com/recipes 

### Get one recipe
GET https://jw-341-projecttwo.onrender.com/recipes/634732b8112fbea1f35de353 

### Create recipe
POST http://jw-341-projecttwo.onrender.com/recipes HTTP/1.1
content-type: application/json

{
    "name": "NewestRecipe",
    "ingredients": ["5 amazing ingredients", "2 amazing ingredients"],
    "directions": ["put them all together", "cook them"],
    "groceryList": ["first", "second", "third"],
    "mealType": "entree"
}

### Update recipe
PUT http://jw-341-projecttwo.onrender.com/recipes/63488f14559883f721478d3e HTTP/1.1
content-type: application/json

{
    "name": "NewestRecipe",
    "ingredients": ["5 amazing ingredients", "2 amazing ingredients"],
    "directions": ["put them all together", "cook them"],
    "groceryList": ["first", "second"],
    "mealType": "entree"
}

### Delete recipe
DELETE http://jw-341-projecttwo.onrender.com/recipes/63488f14559883f721478d3e HTTP/1.1

### Get all days
GET https://jw-341-projecttwo.onrender.com/days 

### Get one day
GET https://jw-341-projecttwo.onrender.com/days/63487ec8d373ea68cf1215f1 

### Update day
PUT https://jw-341-projecttwo.onrender.com/days/6350777ecb10a7354accd434 HTTP/1.1
content-type: application/json

{
    "name": "Monday",
    "mealID":""
}
